name: pc
version: '24.04-0.1'
type: gadget
base: core24
summary: PC gadget for generic devices
description: |
    This gadget enables generic pc devices to work with Ubuntu Core
grade: stable
confinement: strict
icon: icon.png

parts:
  grub-prepare:
    plugin: nil
    stage-packages:
      - shim-signed
      - grub-efi-${CRAFT_TARGET_ARCH}-signed
      - to amd64:
        - grub-pc-bin
    prime: [ -* ]
  grub:
    source: .
    build-packages:
      - grub-common
    plugin: make
    after: [grub-prepare]
    override-build: |
      make install
      cp -r install/* ${CRAFT_PART_INSTALL}
      # snapcraft reads gadget.yaml from project dir
      install -m 644 gadget-${CRAFT_TARGET_ARCH}.yaml ${CRAFT_PROJECT_DIR}/gadget.yaml
