name: xinyi-pc-classic
version: '22.04-0.1'
type: gadget
base: core22
summary: Xinyi PC Classic gadget
description: |
    This gadget enables Xinyi PC Classic systems
confinement: strict
grade: stable

parts:
  boot:
    plugin: nil
    stage-packages:
      - grub-efi-amd64-signed
      - shim-signed
    override-build: |
      set -x
      # grub.conf lets snapd identify grub as the bootloader on boot
      install -m 644 /dev/null "$CRAFT_PART_INSTALL"/grub.conf
    organize:
      usr/lib/shim/shimx64.efi.dualsigned: shim.efi.signed
      usr/lib/grub/x86_64-efi-signed/grubx64.efi.signed: grubx64.efi
    prime:
      - shim.efi.signed
      - grubx64.efi
      - grub.conf
      - usr/share/doc/shim-signed
      - usr/share/doc/grub-efi-amd64-signed
  cmdline:
    plugin: dump
    source: dump
